/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    AuditLogs: () => import('#controllers/admin/audit_logs_controller'),
    Categories: () => import('#controllers/admin/categories_controller'),
    Customers: () => import('#controllers/admin/customers_controller'),
    Dashboard: () => import('#controllers/admin/dashboard_controller'),
    DrugImports: () => import('#controllers/admin/drug_imports_controller'),
    Drugs: () => import('#controllers/admin/drugs_controller'),
    ErrorLogs: () => import('#controllers/admin/error_logs_controller'),
    Reports: () => import('#controllers/admin/reports_controller'),
    Suppliers: () => import('#controllers/admin/suppliers_controller'),
  },
  auth: {
    RegisteredUsers: () => import('#controllers/auth/registered_users_controller'),
    Sessions: () => import('#controllers/auth/sessions_controller'),
  },
  cashier: {
    CounterSales: () => import('#controllers/cashier/counter_sales_controller'),
    Payments: () => import('#controllers/cashier/payments_controller'),
  },
  pharmacy: {
    Prescriptions: () => import('#controllers/pharmacy/prescriptions_controller'),
  },
  shop: {
    Carts: () => import('#controllers/shop/carts_controller'),
    Catalogs: () => import('#controllers/shop/catalogs_controller'),
    Checkouts: () => import('#controllers/shop/checkouts_controller'),
    Orders: () => import('#controllers/shop/orders_controller'),
  },
}
